import React, { useState } from 'react'
import { AuthProvider } from './context/AuthContext'
import Header from './components/Header'
import Home from './pages/Home'
import Services from './pages/Services'
import About from './pages/About'
import Signup from './pages/Signup'
import MyMoves from './pages/MyMoves'
import Inventory from './pages/Inventory'
import Movers from './pages/Movers'
import Booking from './pages/Booking'
import MapView from './pages/MapView'
import Admin from './pages/Admin'
import Login from './pages/Login'
